name: golangci-lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: sudo apt-get install make ftp git bzr curl hwloc libhwloc-dev mesa-opencl-icd ocl-icd-opencl-dev wget -y && sudo apt upgrade -y

      - name: Make dep
        run: make deps

      - name: golangci-lint
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.29
          args: --timeout=30m --skip-dirs='[extern]'
          skip-pkg-cache: true
          skip-build-cache: true
