name: golangci-lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: sudo apt-get install make ftp git bzr curl hwloc libhwloc-dev mesa-opencl-icd ocl-icd-opencl-dev wget -y && sudo apt upgrade -y

      - name: Make dep
        run: make deps

    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        version: "2021.1.1"
